version: 3
services:

  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - '7021:21'
      - '21000-21010:21000-21010'
    environment:
      USERS: 'ftpuser|ftppass'

  ssh:
    image: sickp/alpine-sshd:7.5-r2
    ports:
      - '7022:22'
