source 'https://rubygems.org'

gem 'bfs', path: './core'
gem 'bfs-ftp', path: './ftp'
gem 'bfs-gs', path: './gs'
gem 'bfs-s3', path: './s3'
gem 'bfs-scp', path: './scp'
gem 'bfs-sftp', path: './sftp'

gem 'bcrypt_pbkdf'
gem 'ed25519'
gem 'rake'
gem 'rspec'
gem 'rubocop-bsm'
gem 'webrick'
