name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]
    services:
      ftp:
        image: delfer/alpine-ftp-server
        ports:
          - 7021:21
          - 21000-21010:21000-21010
        env:
          USERS: "user|pass"
      ssh:
        image: sickp/alpine-sshd:7.5-r2
        ports:
          - 7022:22
      sftp:
        image: watersalesman/sftp-alpine
        ports:
          - 7023:22
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          bundle exec rake
